services:
  website:
    build:
      context: .
      dockerfile: ./apps/company-site/Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - salon_dev_network

  cms:
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile
      target: development
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - salon_dev_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salon_dev_network

volumes:
  postgres_data:

networks:
  salon_dev_network:
    name: salon_dev_network
    driver: bridge
