services:
  web:
    build:
      context: ../../
      dockerfile: apps/company-site/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file: apps/company-site/.env
